<?xml version="1.0"?>
<robot name="icart_mini" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_radius" value="0.0725"/>
  <xacro:property name="wheel_thickness" value="0.03"/>
  <xacro:property name="wheel_separation" value="0.2"/>
  <xacro:property name="base_height" value="0.25"/>
  <xacro:property name="wheel_height" value="0.075"/>

  <link name="base_footprint"/>

  <!-- Base Joint -->
  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0.126"/>
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>
  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
      <geometry> 
        <box size="0.4 0.18 0.4"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 0.5"/>
      </material>
    </visual>
    <visual name="back_wheel">
      <origin xyz="-0.12 0.0 0.05" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder  length="0.03" radius="0.04625"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <visual name="front_wheel">
      <origin xyz="0.12 0.0 0.05" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder  length="0.03" radius="0.04625"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 0.5"/>
      </material>
    </visual>
  </link>

  <!-- Left Wheel -->
  <joint type="continuous" name="left_wheel_joint">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin rpy="-${PI/2} 0 0" xyz = "0 ${wheel_separation/2} ${wheel_height}"/>
  </joint> 
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
  </link>
  
  <!-- Right Wheel -->
  <joint type="continuous" name="right_wheel_joint">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin rpy="-${PI/2} 0 0" xyz="0 -${wheel_separation/2} ${wheel_height}" />
  </joint>
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
  </link>

  <!-- LiDAR -->
  <joint name="scan_joint" type="fixed">
    <axis xyz="0 1 0"/>
    <origin xyz="0.15 0 0.18" rpy="0 0 0 "/>
    <parent link="base_link"/>
    <child link="laser"/>
  </joint>
  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0 "/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 0.5"/>
      </material>
    </visual>
  </link>
  
</robot>
